# Generated by Django 4.2.20 on 2025-08-13 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=1000),
        ),
    ]
