# Generated by Django 4.2.20 on 2025-08-14 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0002_alter_user_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cost_price',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
