# Generated by Django 4.2.20 on 2025-08-17 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0003_rename_cost_price_product_quantity_product_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='amount',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='buyer',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='seller',
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network_marketing.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='network_marketing.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('commision recorded', 'commision recorded'), ('not recorded', 'not recorded')], default='commission recorded', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='mlmsetting',
            name='payout_frequency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='commissionconfiguration',
            unique_together={('level', 'category')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'category')},
        ),
    ]
