# Generated by Django 4.2.20 on 2025-08-18 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0005_housing_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referal_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
