# Generated by Django 4.2.20 on 2025-08-19 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0006_alter_user_referal_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoterBuyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_user', to=settings.AUTH_USER_MODEL)),
                ('promoter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promoter_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('promoter', 'buyer')},
            },
        ),
    ]
