# Generated by Django 4.2.20 on 2025-08-19 20:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0007_promoterbuyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='promoterbuyer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='promoterbuyer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
