# Generated by Django 4.2.20 on 2025-09-01 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0009_configuration_package_training_trainingpackage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='commissionconfiguration',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='direct_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='display_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='fast_track_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='incentive_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='indirect_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='loyality_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='profit_share_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='rank_achievement',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commissionconfiguration',
            name='unilevel_bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='service_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='training',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=100),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='commissionconfiguration',
            name='category',
        ),
        migrations.RemoveField(
            model_name='commissionconfiguration',
            name='level',
        ),
        migrations.RemoveField(
            model_name='commissionconfiguration',
            name='percentage',
        ),
        migrations.CreateModel(
            name='UnilevelConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_marketing.category')),
            ],
            options={
                'unique_together': {('level', 'category')},
            },
        ),
    ]
