# Generated by Django 4.2.20 on 2025-09-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0010_alter_commissionconfiguration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuration',
            name='company_revenue_product',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='company_revenue_training',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='product_distribution_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='configuration',
            name='training_distribution_reward',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='package',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
            preserve_default=False,
        ),
    ]
