# Generated by Django 4.2.20 on 2025-09-05 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0011_configuration_company_revenue_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuration',
            name='company_revenue_product_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='company_revenue_training_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='training_distribution_reward_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
