# Generated by Django 4.2.20 on 2025-09-05 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0012_alter_configuration_company_revenue_product_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unilevelconfiguration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
