# Generated by Django 4.2.20 on 2025-09-22 21:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0014_treesetting_package_category_sale_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='commission_type',
            field=models.CharField(choices=[('unilevel commission', 'unilevel commission'), ('direct commission', 'direct commission'), ('indirect commission', 'indirect commission'), ('rank achievement', 'rank achievement'), ('loyality bonus', 'loyality bonus'), ('fast track bonus', 'fast track bonus'), ('display bonus', 'display bonus'), ('incentive bonus', 'incentive bonus'), ('profit share bonus', 'profit share bonus')], default='unilevel bonus', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='direct_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='display_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='fast_track_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='incentive_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='indirect_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='loyality_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='commissionconfiguration',
            name='unilevel_bonus',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='company_revenue_product_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='company_revenue_training_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='product_disrtribution_reward_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='configuration',
            name='training_distribution_reward_percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
        migrations.AlterField(
            model_name='unilevelconfiguration',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
