# Generated by Django 4.2.20 on 2025-09-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_marketing', '0016_rank_user_rank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mlmsetting',
            old_name='min_withdrawal_amount',
            new_name='business_volume_amount_in_sales',
        ),
        migrations.AddField(
            model_name='rank',
            name='minimum_business_volume',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=1000),
            preserve_default=False,
        ),
    ]
